### ISSUE TITLE
Support more formats

### ISSUE THREAD

**Issue by queer** [queer/utt#1]
- [x] base64
- [x] rot13
- [ ] ~~base16~~

**Comment by jplattel** [comment]
If possible supporting Python objects would be awesome! ✌️

(I frequently have those on the clipboard so `pbpaste | utt ...`, saves me one step of dumping them to JSON first)

**Comment by queer** [comment]
@jplattel Can you open a separate issue for that?

**Comment by jplattel** [comment]
Sure will do, thanks! 👍
