### ISSUE TITLE
Add support for python objects/lists

### ISSUE THREAD

**Issue by jplattel** [queer/utt#6]
It would be nice if python objects / lists are also supported. I've often found myself changing code to dump a simple python object or a list to JSON or YAML. If I could just copy the object and run it through `utt` with `pbpaste | utt ...` for example, that'll be great! 

Here are a couple of examples on how this could work:

For a python list: 

```bash
$ python -c "print([1,2,3])" | utt -i python -o yaml
---
- 1
- 2
- 3
$ 
```

And for a python object:

```bash
$ python -c 'print({"key": "value", "list": [1,2,3]})' | utt -i python -o yaml
---
key: value 
list:
 - 1
 - 2
 - 3
$ 
```

For the object it might be nice if a value is quoted when required? Key and values might be unicode/byte encoded, thus having a prefix of u/b which might throw the current JSON encoder off..

**Comment by queer** [comment]
The more I look into it, the more it seems it requires having a Python installation + the ability to shell out to it. I couldn't coerce the GraalVM Polyglot API into running Python code, nor did Jython work correctly.

**Comment by queer** [comment]
Python is a supported input format as of 0.0.5 :D
